import type { Job } from './types'

export const DEMO_JOBS: Job[] = [
  {
    id: 'demo-1',
    source: 'demo',
    title: 'Développeur Full-Stack React / Node.js',
    company: 'Swisscom AG',
    location: 'Berne',
    canton: 'BE',
    description:
      'Rejoignez notre équipe engineering pour développer les prochaines générations de services numériques. Vous travaillerez sur une stack moderne : React 18, TypeScript, Node.js, PostgreSQL. Environnement agile, rituels Scrum, déploiement continu sur AWS.',
    requirements:
      'React, TypeScript, Node.js, PostgreSQL, Docker, Git, CI/CD. 3+ ans d\'expérience. Bonnes pratiques TDD appréciées.',
    salaryMin: 110000,
    salaryMax: 140000,
    contractType: 'CDI',
    workloadMin: 80,
    workloadMax: 100,
    remote: true,
    languagesRequired: ['FR', 'DE'],
    url: 'https://www.job-room.ch',
    stellennummer: 'AVA-2024-00001',
    reportingObligation: false,
    publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    matchScore: 94,
  },
  {
    id: 'demo-2',
    source: 'demo',
    title: 'Data Engineer — Plateforme BI',
    company: 'UBS AG',
    location: 'Zürich',
    canton: 'ZH',
    description:
      'Au sein de l\'équipe Data Platform, vous concevrez et maintiendrez les pipelines de données critiques pour les activités de banque d\'investissement. Technologies : Apache Spark, dbt, Snowflake, Airflow.',
    requirements:
      'Python, Spark, dbt, Snowflake, Airflow. 5+ ans d\'expérience data engineering. Anglais courant obligatoire.',
    salaryMin: 130000,
    salaryMax: 160000,
    contractType: 'CDI',
    workloadMin: 100,
    workloadMax: 100,
    remote: false,
    languagesRequired: ['EN', 'DE'],
    url: 'https://www.job-room.ch',
    stellennummer: 'AVA-2024-00002',
    reportingObligation: true,
    publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    matchScore: 87,
  },
  {
    id: 'demo-3',
    source: 'demo',
    title: 'UX / UI Designer — Applications Mobiles',
    company: 'Migros Bank',
    location: 'Zürich',
    canton: 'ZH',
    description:
      'Conception de l\'expérience utilisateur de notre nouvelle application bancaire mobile. Vous travaillerez en étroite collaboration avec les équipes produit et engineering. Figma, Design System, tests utilisateurs.',
    requirements:
      'Figma, prototypage, recherche utilisateur, design system. 3+ ans en UX/UI mobile. Portfolio requis.',
    salaryMin: 95000,
    salaryMax: 120000,
    contractType: 'CDI',
    workloadMin: 80,
    workloadMax: 100,
    remote: true,
    languagesRequired: ['FR', 'DE'],
    url: 'https://www.job-room.ch',
    stellennummer: 'AVA-2024-00003',
    reportingObligation: false,
    publishedAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    matchScore: 82,
  },
  {
    id: 'demo-4',
    source: 'demo',
    title: 'DevOps Engineer — Cloud & Kubernetes',
    company: 'EPFL (École Polytechnique Fédérale de Lausanne)',
    location: 'Lausanne',
    canton: 'VD',
    description:
      'Rejoignez l\'équipe infrastructure de l\'EPFL pour gérer notre cluster Kubernetes multi-tenant. Vous serez responsable de l\'automatisation, de la sécurité et de la disponibilité des services académiques.',
    requirements:
      'Kubernetes, Terraform, Helm, Prometheus, GitOps. Expérience en milieu académique ou recherche appréciée.',
    salaryMin: 100000,
    salaryMax: 130000,
    contractType: 'CDI',
    workloadMin: 100,
    workloadMax: 100,
    remote: false,
    languagesRequired: ['FR', 'EN'],
    url: 'https://www.job-room.ch',
    stellennummer: 'AVA-2024-00004',
    reportingObligation: false,
    publishedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    matchScore: 76,
  },
  {
    id: 'demo-5',
    source: 'demo',
    title: 'Product Manager — Fintech B2C',
    company: 'Neon Bank',
    location: 'Zürich',
    canton: 'ZH',
    description:
      'En tant que PM, vous définirez la roadmap produit de notre application bancaire néobanque. OKRs, discovery produit, coordination engineering/design, go-to-market. Startup en forte croissance (350K utilisateurs).',
    requirements:
      'Expérience PM 3+ ans en fintech ou B2C digital. Maîtrise des outils analytics (Mixpanel, Amplitude). Excellent communicant.',
    salaryMin: 115000,
    salaryMax: 145000,
    contractType: 'CDI',
    workloadMin: 100,
    workloadMax: 100,
    remote: true,
    languagesRequired: ['DE', 'EN'],
    url: 'https://www.job-room.ch',
    stellennummer: 'AVA-2024-00005',
    reportingObligation: false,
    publishedAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    matchScore: 71,
  },
  {
    id: 'demo-6',
    source: 'demo',
    title: 'Backend Engineer — Java / Spring Boot',
    company: 'SIX Group AG',
    location: 'Zürich',
    canton: 'ZH',
    description:
      'Développement et maintenance des systèmes de clearing et de règlement de SIX. Environnement critique, haute disponibilité, volumes importants. Spring Boot, microservices, Kafka, Oracle.',
    requirements:
      'Java 17+, Spring Boot, Kafka, Oracle DB. Expérience en systèmes financiers critiques. Certification AWS un plus.',
    salaryMin: 120000,
    salaryMax: 155000,
    contractType: 'CDI',
    workloadMin: 100,
    workloadMax: 100,
    remote: false,
    languagesRequired: ['DE', 'EN'],
    url: 'https://www.job-room.ch',
    stellennummer: 'AVA-2024-00006',
    reportingObligation: true,
    publishedAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    matchScore: 68,
  },
]

export const DEMO_TOTAL = DEMO_JOBS.length
